### ISSUE TITLE
[Contacts] Full To-Do List

### ISSUE THREAD

**Issue by asd1o1** [asd1o1/Programming-Level-1#50]
**Things To Do**
===
### Directory organisation
- [x] Accounts file to list all usernames [38e835db4896813a036d72b679b52b218f736c06]
- [x] Directory with name of user generated on account creation [38e835db4896813a036d72b679b52b218f736c06]
- [x] File with name of user generated on account creation, includes password and contacts [38e835db4896813a036d72b679b52b218f736c06]
- [x] Organize contacts in user file in alphabetical order [dd4b8abee4fdeba0355189a7ba78ca600446f5a2]
- [x] Config file with options on how to format output [78f678806aab54a3b8eba44dd9d4ab40e0ea77ca]
- [x] File for each user formatted with first name on first line, followed by last name on second, number of emails on third, number of phone numbers on fourth, followed by all emails, then all phone numbers [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]

### Config file
- [x] `bool firstNameFirst = true` for first name to be shown before last name [78f678806aab54a3b8eba44dd9d4ab40e0ea77ca]
- [x] `bool emailBeforePhone = true` for the emails to be shown before phone numbers [78f678806aab54a3b8eba44dd9d4ab40e0ea77ca]
- [x] `bool formatPhone = true` to show formatting on phone number [78f678806aab54a3b8eba44dd9d4ab40e0ea77ca]
- [x] `char formatPhoneChar = '-'` to change the character used to space phone numbers [78f678806aab54a3b8eba44dd9d4ab40e0ea77ca]

### Login
- [x] Account Wizard that creates necessary files and directories [38e835db4896813a036d72b679b52b218f736c06]
- [x] Login Wizard that checks username and password to login [59b7b67eb348b890d7dd226c3978d14316de55ea]
- [x] Account Wizard checks to make sure username does not match any existing ones [541b33b2b1d8e9d8ed318ea7a85a06b6b2152c45]
- [x] Account Wizard checks to make sure password is 8 chars or longer [50642ac164d1a7f32cc37a20731a703029d2e7cb]
- [x]  Create Developer menu for full control on deleting users, changing user passwords, etc. [a6dff72f292b3c2390f179a02573e46b452804e8]
- [x] Fix deletionWizard() in developer menu [ffc35fc82b4ab348bdc49fed2677105e1ca4ce78]
- [x] Fix inability to create user longer with more than 4 characters [a489a942843a488cd226b094e7a492a379ab306a]

### Logout
- [x] Fix logout not working [41217fa0fcf2acf4f6008736ba53e2561efdf0dd]

### List of contacts
- [x] Read names of contact files from user file and load them one by one [e036f91d69ced621db3f54e539aa4759558556ef]
- [x] Format output based on config file [e036f91d69ced621db3f54e539aa4759558556ef]

### Editing a contact
- [x] Choose contact to edit by number [f61846f5c979ce94a20db3714689b91bb7e59537]
- [x] Show preview of contact based on config file [f61846f5c979ce94a20db3714689b91bb7e59537]
- [x] Menu options to change first and last names [f61846f5c979ce94a20db3714689b91bb7e59537]
- [x] Menu option to add emails [f61846f5c979ce94a20db3714689b91bb7e59537]
- [x] Menu option to add phones [f61846f5c979ce94a20db3714689b91bb7e59537]
- [x] Menu option to change emails [f61846f5c979ce94a20db3714689b91bb7e59537]
- [x] Menu option to change phones [1e98f38377a6691102976068aedca42590e2a3e1]
- [x] Menu option to remove emails [1e98f38377a6691102976068aedca42590e2a3e1]
- [x] Menu option to remove phones [1e98f38377a6691102976068aedca42590e2a3e1]
- [x] Update changes after done
- [x] Fix bug where program stops responding after case ends [1e98f38377a6691102976068aedca42590e2a3e1]
- [x] Fix bug where emails and phone numbers are weirdly merged [3a9837588e36a2f2e86ace9a60a6993002946359]

### Adding a new contact
- [x] Required prompt for first and last name [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]
- [x] Prompt for number of emails to add (can be zero) [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]
- [x] If non-zero, prompt for email as many times as necessary [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]
- [x] Prompt for number of phone numbers to add (can be zero) [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]
- [x] If non-zero, prompt for email as many times as necessary [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]
- [x] Create file by appending first and last names and use camel case [e80fb3b972bb67d889f4c0b20b1abdcb3485dc7d]

### Removing a contact
- [x] Remove file from user directory [7595c59250192ac1d53478173480aea25828b578]
- [x] Remove reference in user file [7595c59250192ac1d53478173480aea25828b578]

### Settings sub menu
- [x] ~Option to change username~ Yeah... nope.
- [x] Option to change password [a495360e885eee5f7cffd2ff2f49ace40d6eda89]
- [x] Fix first contact being deleted when changing password [a562bd7a033dfc26012931c3cb0d7078870e278d]
- [x] Option to change config file [0255be25063ee4860790d73d69dc17907ffa4c6f]
- [x] Option to remove all contacts [c21b6880faccad5ec4c6141425e3c8ba790e9c90]
- [x] Option to delete account [19e73b530492275feeed67f738c2ea645cdcb9a7]

### Optimization and code clarity
- [x] Remove useless variables [546ad40572d4535032acaf9b2f0ca18afdc280f2]
- [x] Add blank lines to separate code where necessary
- [x] Homogenize similar code segments in different functions [546ad40572d4535032acaf9b2f0ca18afdc280f2]
- [x] Separate functions into multiple .h and .cpp files [546ad40572d4535032acaf9b2f0ca18afdc280f2]

**Comment by asd1o1** [comment]
**Things To Do**
===
### Directory organisation
[x] Accounts file to list all usernames
[x] Directory with name of user generated on account creation
[x] File with name of user generated on account creation, includes username and password
[ ] Config file with options on how to format output
[ ] File for each user formatted with first name on first line, followed by last name on second, number of emails on third, number of phone numbers on fourth, followed by all emails, then all phone numbers

### Config file
[ ] `bool firstNameFirst = true` for first name to be shown before last name
[ ] `bool emailBeforePhone = true` for the emails to be shown before phone numbers
[ ] `bool formatPhone = true` to show formatting on phone number
[ ] `char formatPhoneChar = '-'` to change the character used to space phone numbers

### Login
[x] Account Wizard that creates necessary files and directories
[x] Login Wizard that checks username and password to login
[ ] Password encryption [Optional]
[ ]  Create Developer menu for full control on deleting users, changing user passwords, etc.

### Logout
[ ] Fix logout not working

### List of contacts
[ ] Read names of contact files from user file and load them one by one
[ ] Format output based on config file

### Editing a contact
[ ] Choose contact to edit by first name or last name, as defined in config file
[ ] Show preview of contact based on config file
[ ] Menu options to change first and last names
[ ] Menu options to add or remove emails or phone numbers
[ ] Menu option to edit current email(s) or phone number(s)
[ ] Update changes when after every change

### Adding a new contact
[ ] Required prompt for first and last name
[ ] Prompt for number of emails to add (can be zero)
[ ] If non-zero, prompt for email as many times as necessary
[ ] Prompt for number of phone numbers to add (can be zero)
[ ] If non-zero, prompt for email as many times as necessary
[ ] Create file by appending first and last names and use camel case

### Settings sub menu
[ ] Option to change username
[ ] Option to change password
[ ] Option to change config file
[ ] Option to reset all contacts
[ ] Option to delete account
